# Generated by Django 3.1.7 on 2021-03-28 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_following_like_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='posts',
            new_name='post',
        ),
    ]
